version: "3.8"

services:
  master:
    build:
      context: .
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      - ROLE=master
      - MASTER_HOST=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir

  worker1:
    build:
      context: .
    expose:
      - "6121"
      - "6122"
    depends_on:
      - master
    links:
      - "master:master"
    environment:
      - ROLE=worker
      - MASTER_HOST=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir
    deploy:
      replicas: 1
      resources:
        limits:
          # cpus: '0.50'
          cpus: '3.0'
          memory: 2048M 


  # worker2:
    # build:
    #   context: .
    # expose:
    #   - "6121"
    #   - "6122"
    # depends_on:
    #   - master
    # links:
    #   - "master:master"
    # environment:
    #   - ROLE=worker
    #   - MASTER_HOST=master
    # volumes:
    #   - ./checkpoint-dir:/checkpoint-dir
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 512M 